# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search_mode', '0002_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('search_timestamp',), 'verbose_name': 'login attempt', 'verbose_name_plural': 'login attempts'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='search_date',
        ),
        migrations.AddField(
            model_name='request',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address'),
        ),
        migrations.AddField(
            model_name='request',
            name='search_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='user-agent'),
        ),
        migrations.AlterField(
            model_name='request',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
